name: REUSE License Compliance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  reuse:
    name: REUSE License Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install REUSE
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipx
          pipx install reuse

      - name: Check REUSE compliance
        run: |
          reuse lint 